name: null

image:
  repository: null
  tag: latest
  pullPolicy: IfNotPresent

replicas: 2

port: 8080

service:
  port: 80
  loadBalancer:
    enabled: false
    scheme: internal   # internal | external
    sourceRanges: []
    name: null

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
