name: web
type: deployment

replicas: 2

port: 8080

service:
  port: 80
  loadBalancer:
    enabled: true
    scheme: internal
    name: sentinel-backend-web

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
